# Generated by Django 2.2.4 on 2022-06-23 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0002_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_wished', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish', to='belt_app.Items')),
                ('who_wished', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish', to='belt_app.Users')),
            ],
        ),
    ]
