# Generated by Django 2.2.4 on 2022-06-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0003_wishes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wishes',
        ),
    ]
